# Generated by Django 5.0.3 on 2024-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_area_client_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
