# Generated by Django 5.0.3 on 2024-04-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
