# Generated by Django 5.0.3 on 2024-04-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_follow_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_active',
        ),
    ]
